name: Git pull en Web Tier
run-name: ${{ github.actor }} actualizó el repositorio Web Tier. 🚀
on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 'public'
          container_name: '$web'
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          sync: 'true'
